version: '3.9'


services:
  db:
    image: mysql
    restart: always
    ports:
      - 33066:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gochat

    volumes:
      - .DBData:/var/usr/bin